// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borrador.Entities;

public partial class Estado
{
    /// <summary>
    /// Identificador unico de los estados que esten registrados en esta tabla.
    /// </summary>
    public int IdEstado { get; set; }

    /// <summary>
    /// Nombre del estado que se registre (PENDIENTE, APROBADO, PRESTADO, etc).
    /// </summary>
    public string Estado1 { get; set; }

    /// <summary>
    /// Campo de descripcion donde explicar brevemente que hara el estado que se registre.
    /// </summary>
    public string Descripcion { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que se cree un registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que cree un registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea modificado.
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara que usuario por su id que modifique un registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea eliminado (de forma lógica).
    /// </summary>
    public DateTime? FechaElim { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que haya eliminado un registro de esta tabla.
    /// </summary>
    public int? UsuarioElimId { get; set; }

    /// <summary>
    /// Atributo booleano que indicara si un registro este eliminado o no.
    /// </summary>
    public bool Elimino { get; set; }

    public virtual ICollection<Libro> Libros { get; set; } = new List<Libro>();

    public virtual Usuario UsuarioCreacion { get; set; }

    public virtual Usuario UsuarioElim { get; set; }
}