// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borrador.Entities;

public partial class Libro
{
    public int IdLibro { get; set; }

    public string Titulo { get; set; }

    public int AutorId { get; set; }

    public string Isbn { get; set; }

    public DateTime? FechaPublicacion { get; set; }

    public int? CantidadEjemplares { get; set; }

    /// <summary>
    /// Atributo del estado en el que se encuentre el libro (PRESTADO, DISPONIBLE, etc).
    /// </summary>
    public int EstadoId { get; set; }

    public int CategoriaId { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que se cree un registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que cree un registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea modificado.
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara que usuario por su id que modifique un registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea eliminado (de forma lógica).
    /// </summary>
    public DateTime? FechaElim { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que haya eliminado un registro de esta tabla.
    /// </summary>
    public int? UsuarioElimId { get; set; }

    /// <summary>
    /// Atributo booleano que indicara si un registro este eliminado o no.
    /// </summary>
    public bool Elimino { get; set; }

    public virtual Autore Autor { get; set; }

    public virtual Categoria Categoria { get; set; }

    public virtual Estado Estado { get; set; }

    public virtual ICollection<Prestamo> Prestamos { get; set; } = new List<Prestamo>();

    public virtual Usuario UsuarioCreacion { get; set; }

    public virtual Usuario UsuarioElim { get; set; }
}