// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borrador.Entities;

/// <summary>
/// Identificador del usuario al cual se le realizara el prestamo (debe de ser un usuario de tipo estudiante).
/// </summary>
public partial class Prestamo
{
    /// <summary>
    /// Identificador unico de cada prestamo
    /// </summary>
    public int IdPrestamo { get; set; }

    /// <summary>
    /// Codigo de prestamo, debe ser un codigo unico por cada prestamo
    /// </summary>
    public string CodigoPrestamo { get; set; }

    /// <summary>
    /// Identificador del libro que se este prestando.
    /// </summary>
    public int LibroId { get; set; }

    /// <summary>
    /// Identificador del usuario que realizara el prestamo (no debe ser un usuario de tipo administrador).
    /// </summary>
    public int UsuarioId { get; set; }

    /// <summary>
    /// Fecha en la que se realice el prestamo.
    /// </summary>
    public DateTime? FechaPrestamo { get; set; }

    /// <summary>
    /// Fecha estima en la que se deberia de entregar el libro prestado.
    /// </summary>
    public DateTime? FechaDevolucion { get; set; }

    /// <summary>
    /// Fecha real en la que el usuario retorno el libro prestado.
    /// </summary>
    public DateTime? FechaRealDevolucion { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que se cree un registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que cree un registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea modificado.
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara que usuario por su id que modifique un registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea eliminado (de forma lógica)
    /// </summary>
    public DateTime? FechaElim { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que haya eliminado un registro de esta tabla.
    /// </summary>
    public int? UsuarioElimId { get; set; }

    /// <summary>
    /// Atributo booleano que indicara si un registro este eliminado o no.
    /// </summary>
    public bool Elimino { get; set; }

    public virtual Libro Libro { get; set; }

    public virtual Usuario Usuario { get; set; }

    public virtual Usuario UsuarioCreacion { get; set; }

    public virtual Usuario UsuarioElim { get; set; }
}