// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borrador.Entities;

public partial class Role
{
    /// <summary>
    /// Este atributo sera el identificador unico de los roles que se registren en esta tabla.
    /// </summary>
    public byte IdRol { get; set; }

    /// <summary>
    /// Nombre del rol que se registre, que no puede exceder los 50 caracteres.
    /// </summary>
    public string Nombre { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que se cree un registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que cree un registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea modificado.
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara que usuario por su id que modifique un registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea eliminado (de forma lógica).
    /// </summary>
    public DateTime? FechaElim { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que haya eliminado un registro de esta tabla.
    /// </summary>
    public int? UsuarioElimId { get; set; }

    /// <summary>
    /// Atributo booleano que indicara si un registro este eliminado o no.
    /// </summary>
    public bool Elimino { get; set; }

    public virtual Usuario UsuarioCreacion { get; set; }

    public virtual Usuario UsuarioElim { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}