// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Borrador.Entities;

public partial class Usuario
{
    /// <summary>
    /// Este atributo sera el identificador unico de los usuarios que se registren en esta tabla.
    /// </summary>
    public int IdUsuario { get; set; }

    public byte RolId { get; set; }

    /// <summary>
    /// Este atributo sera nombre de los usuarios que se registren en esta tabla.
    /// </summary>
    public string Nombre { get; set; }

    /// <summary>
    /// Este atributo sera el correo de los usuarios que se registren en esta tabla.
    /// </summary>
    public string Correo { get; set; }

    /// <summary>
    /// Este atributo sera la clave de los usuarios que se registren en esta tabla.
    /// </summary>
    public string Clave { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que se cree un registro.
    /// </summary>
    public DateTime FechaCreacion { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que cree un registro.
    /// </summary>
    public int UsuarioCreacionId { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea modificado.
    /// </summary>
    public DateTime? FechaMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara que usuario por su id que modifique un registro.
    /// </summary>
    public int? UsuarioMod { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara la fecha en la que un registro sea eliminado (de forma lógica)
    /// </summary>
    public DateTime? FechaElim { get; set; }

    /// <summary>
    /// Atributo de auditoria que registrara el id del usuario que haya eliminado un registro de esta tabla.
    /// </summary>
    public int? UsuarioElimId { get; set; }

    /// <summary>
    /// Atributo booleano que indicara si un registro este eliminado o no.
    /// </summary>
    public bool Elimino { get; set; }

    public virtual ICollection<Autore> AutoreUsuarioCreacions { get; set; } = new List<Autore>();

    public virtual ICollection<Autore> AutoreUsuarioElims { get; set; } = new List<Autore>();

    public virtual ICollection<Categoria> CategoriaUsuarioCreacions { get; set; } = new List<Categoria>();

    public virtual ICollection<Categoria> CategoriaUsuarioElims { get; set; } = new List<Categoria>();

    public virtual ICollection<Estado> EstadoUsuarioCreacions { get; set; } = new List<Estado>();

    public virtual ICollection<Estado> EstadoUsuarioElims { get; set; } = new List<Estado>();

    public virtual ICollection<Usuario> InverseUsuarioElim { get; set; } = new List<Usuario>();

    public virtual ICollection<Libro> LibroUsuarioCreacions { get; set; } = new List<Libro>();

    public virtual ICollection<Libro> LibroUsuarioElims { get; set; } = new List<Libro>();

    public virtual ICollection<Prestamo> PrestamoUsuarioCreacions { get; set; } = new List<Prestamo>();

    public virtual ICollection<Prestamo> PrestamoUsuarioElims { get; set; } = new List<Prestamo>();

    public virtual ICollection<Prestamo> PrestamoUsuarios { get; set; } = new List<Prestamo>();

    public virtual Role Rol { get; set; }

    public virtual ICollection<Role> RoleUsuarioCreacions { get; set; } = new List<Role>();

    public virtual ICollection<Role> RoleUsuarioElims { get; set; } = new List<Role>();

    public virtual Usuario UsuarioElim { get; set; }
}